### ISSUE TITLE
File storage directory permission problems.

### ISSUE THREAD

**Issue by arjunadeltoso** [bitnami/bitnami-docker-phabricator#120]
We are using bitnami phabricator docker and running into something that looks like a misconfiguration of the container.

This is our docker-compose.yml

```
$ cat docker-compose.yml 
# Launch from makefile

version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--innodb_buffer_pool_size=1600M --max_allowed_packet=33554432 --sql_mode=STRICT_ALL_TABLES
    volumes:
      - 'mariadb_data:/phabricator/db'
    networks:
      - app-tier
  phabricator:
    image: 'bitnami/phabricator:latest'
    restart: always
    environment:
      - PHABRICATOR_HOST=REDACTED
      - VIRTUAL_HOST=REDACTED
      - PHABRICATOR_USERNAME=REDACTED
      - PHABRICATOR_PASSWORD=REDACTED
      - PHABRICATOR_EMAIL=REDACTED
      # Mail settings
      - SMTP_HOST=REDACTED
      - SMTP_PORT=587
      - SMTP_USER=REDACTED
      - SMTP_PASSWORD=REDACTED
      - SMTP_PROTOCOL=tls
    labels:
      kompose.service.type: nodeport
    ports:
      - 'REDACTED:80'
      - 'REDACTED:443'
    volumes:
      - 'phabricator_data:/phabricator/data'
      - '/tmp/pinterest-linters:/opt/bitnami/pinterest-linters'
    depends_on:
      - mariadb
    networks:
      - app-tier
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

and this the Makefile

```
deploy-prod-phabricator:
        docker stop phabricator || true
        docker rm phabricator || true
        $(MAKE) fetch-pinterest-linters;
        docker volume create --name phabricator_data || true
        docker run -d --name phabricator -p REDACTED:80 -p REDACTED:443 \
        --net phabricator-tier \
        --restart=always \
        --volume phabricator_data:/bitnami \
        --volume $(PWD)/conf:/etc/phabricator \
        --volume /opt/vendor/pinterest-linters:/opt/bitnami/pinterest-linters \
        --env PHABRICATOR_HOST=$(PHABRICATOR_HOST) --env VIRTUAL_HOST=$(PHABRICATOR_HOST) \
        --env PHABRICATOR_USERNAME=REDACTED --env PHABRICATOR_PASSWORD=REDACTED \
        --env PHABRICATOR_EMAIL=REDACTED --env SMTP_HOST=REDACTED \
        --env SMTP_PORT=587 --env SMTP_USER=REDACTED \
        --env SMTP_PASSWORD=REDACTED --env SMTP_PROTOCOL=tls \
        bitnami/phabricator:latest;
        sleep 45
        docker exec phabricator /opt/bitnami/phabricator/bin/config set phabricator.base-uri https://$(PHABRICATOR_HOST)
        sleep 5
        docker exec phabricator /bin/bash -c 'apt-get update && apt-get -y install python-pygments'
        sleep 5
        docker exec phabricator /opt/bitnami/phabricator/bin/config set cluster.mailers --stdin < /etc/phabricator/mailer.json
```

but the file storage directories are owned by `daemon:daemon` and this makes storing files fail

```
root@a9f470a3ca63:/# phd log
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000] [2019-04-19 00:27:14] EXCEPTION: (PhutilProxyException) Error while executing Task ID 416343. {>} (PhutilAggregateException) All storage engines failed to write file:
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]     - PhabricatorLocalDiskFileStorageEngine: CommandException: Command failed with error #1!
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       COMMAND
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       mkdir -p '/opt/bitnami/phabricator/data/f5/c2'
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       STDOUT
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       (empty)
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       STDERR
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]       mkdir: cannot create directory '/opt/bitnami/phabricator/data/f5/c2': Permission denied
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]        at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:391]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000] arcanist(head=stable, ref.stable=7b6a9a93f4a4), phabricator(head=stable, ref.stable=8c5aceec6090), phutil(head=stable, ref.stable=47cfa511ca67)
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #0 <#3> ExecFuture::resolvex() called at [<phutil>/src/future/exec/execx.php:17]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #1 <#3> execx(string, string) called at [<phabricator>/src/applications/files/engine/PhabricatorLocalDiskFileStorageEngine.php:58]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #2 <#3> PhabricatorLocalDiskFileStorageEngine::writeFile(string, array) called at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:539]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #3 <#3> PhabricatorFile::writeToEngine(PhabricatorLocalDiskFileStorageEngine, string, array) called at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:370]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #4 <#2> PhabricatorFile::buildFromFileData(string, array) called at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:436]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #5 <#2> PhabricatorFile::newFromFileData(string, array) called at [<phabricator>/src/applications/files/uploadsource/PhabricatorFileUploadSource.php:170]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #6 <#2> PhabricatorFileUploadSource::writeSingleFile() called at [<phabricator>/src/applications/files/uploadsource/PhabricatorFileUploadSource.php:76]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #7 <#2> PhabricatorFileUploadSource::uploadFile() called at [<phabricator>/src/applications/diffusion/query/DiffusionFileFutureQuery.php:114]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #8 <#2> DiffusionFileFutureQuery::executeQuery() called at [<phabricator>/src/applications/diffusion/query/DiffusionQuery.php:96]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #9 <#2> DiffusionQuery::execute() called at [<phabricator>/src/applications/diffusion/query/DiffusionFileFutureQuery.php:60]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #10 <#2> DiffusionFileFutureQuery::respondToConduitRequest(ConduitAPIRequest) called at [<phabricator>/src/applications/diffusion/conduit/DiffusionRawDiffQueryConduitAPIMethod.php:44]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #11 <#2> DiffusionRawDiffQueryConduitAPIMethod::getResult(ConduitAPIRequest) called at [<phabricator>/src/applications/diffusion/conduit/DiffusionQueryConduitAPIMethod.php:158]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #12 <#2> DiffusionQueryConduitAPIMethod::execute(ConduitAPIRequest) called at [<phabricator>/src/applications/conduit/method/ConduitAPIMethod.php:123]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #13 <#2> ConduitAPIMethod::executeMethod(ConduitAPIRequest) called at [<phabricator>/src/applications/conduit/call/ConduitCall.php:131]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #14 <#2> ConduitCall::executeMethod() called at [<phabricator>/src/applications/conduit/call/ConduitCall.php:81]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #15 <#2> ConduitCall::execute() called at [<phabricator>/src/applications/diffusion/query/DiffusionQuery.php:82]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #16 <#2> DiffusionQuery::callConduitWithDiffusionRequest(PhabricatorUser, DiffusionGitRequest, string, array) called at [<phabricator>/src/applications/differential/engine/DifferentialDiffExtractionEngine.php:57]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #17 <#2> DifferentialDiffExtractionEngine::newDiffFromCommit(PhabricatorRepositoryCommit) called at [<phabricator>/src/applications/differential/engine/DifferentialDiffExtractionEngine.php:241]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #18 <#2> DifferentialDiffExtractionEngine::updateRevisionWithCommit(DifferentialRevision, PhabricatorRepositoryCommit, array, PhabricatorDaemonContentSource) called at [<phabricator>/src/applications/repository/worker/commitmessageparser/PhabricatorRepositoryCommitMessageParserWorker.php:247]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #19 <#2> PhabricatorRepositoryCommitMessageParserWorker::updateCommitData(DiffusionCommitRef) called at [<phabricator>/src/applications/repository/worker/commitmessageparser/PhabricatorRepositoryCommitMessageParserWorker.php:42]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #20 <#2> PhabricatorRepositoryCommitMessageParserWorker::parseCommit(PhabricatorRepository, PhabricatorRepositoryCommit) called at [<phabricator>/src/applications/repository/worker/PhabricatorRepositoryCommitParserWorker.php:51]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #21 <#2> PhabricatorRepositoryCommitParserWorker::doWork() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:123]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #22 <#2> PhabricatorWorker::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/storage/PhabricatorWorkerActiveTask.php:171]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #23 <#2> PhabricatorWorkerActiveTask::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorTaskmasterDaemon.php:22]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #24 PhabricatorTaskmasterDaemon::run() called at [<phutil>/src/daemon/PhutilDaemon.php:219]
Daemon 158514 STDE [Fri, 19 Apr 2019 00:27:14 +0000]   #25 PhutilDaemon::execute() called at [<phutil>/scripts/daemon/exec/exec_daemon.php:131]
Daemon 158514 FAIL [Fri, 19 Apr 2019 00:27:14 +0000] Process exited with error 255.
Daemon 158514 WAIT [Fri, 19 Apr 2019 00:27:14 +0000] Waiting 5 second(s) to restart process.
```

leading to commits not being processed and diffs not closed.

Our current patch is to run every minute a cronjob within the container

```
* * * * *       root chown -R daemon:phabricator /bitnami/phabricator/data && chmod -R 775 /bitnami/phabricator/data
```

but this is far from ideal and doesn't guarantee that phabricator will be able to write in those directories 100% of the times.

Any suggestion on a proper fix (without having to switch to mysql file storage)?

**Comment by andresbono** [comment]
Hi @arjunadeltoso, you are defining a `docker-compose.yml` file but you are not using it in the `Makefile`, right?

We cannot reproduce your issue. We execute several tests that upload files to the application every time we do a release of the container and we didn't see that behavior.

In order to help us to reproduce the issue, can you tell us the specific version of the container that you are using? You can execute the following command:

```
docker exec -it phabricator env | grep BITNAMI_IMAGE_VERSION
```

- Andrés B.

**Comment by arjunadeltoso** [comment]
@andresbono here it is
```
$ docker exec -it phabricator env | grep BITNAMI_IMAGE_VERSION
BITNAMI_IMAGE_VERSION=2018.12.0-r0
```
I didn't manage the setup of phabricator so can't really speak on that docker-compose.yml but as you mention there is no `docker build` or `docker-compose up` so it might be unused.
Thanks for looking into the issue!

**Comment by andresbono** [comment]
@arjunadeltoso,

That version is pretty old and may have bugs that we have fixed in more recent versions of the application.

Is it possible for you to upgrade to the latest version of the application? Latest version is:

```
docker run --rm -it bitnami/phabricator:latest env | grep BITNAMI_IMAGE_VERSION
BITNAMI_IMAGE_VERSION=2019.14.0-debian-9-r10
```

**Comment by arjunadeltoso** [comment]
@andresbono I'll try as soon as possible, meanwhile do you mind sharing the expected permissions of that directory so I can check if the upgrade worked fine.
Thanks

**Comment by andresbono** [comment]
The ownership configuration is still `daemon:daemon`, but the application is able to write there:

```
$ docker exec -it debian-9_phabricator_1 ls -la /bitnami/phabricator/data
total 40
drwxr-xr-x 10 daemon daemon 4096 Apr 24 06:53 .
drwxr-xr-x  5 root   root   4096 Apr 24 06:53 ..
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 05
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 3b
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 52
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 64
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 76
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 85
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 96
drwxr-xr-x  3 daemon daemon 4096 Apr 24 06:53 bb
```

**Comment by arjunadeltoso** [comment]
I've updated to the last version but still having the same issue, here the details:
```
root@4c6d86bfe91b:/#  env | grep BITNAMI_IMAGE_VERSION
BITNAMI_IMAGE_VERSION=2019.14.0-debian-9-r10
```

```
root@4c6d86bfe91b:/# ls -lad /opt/bitnami/phabricator/data  
lrwxrwxrwx 1 root root 25 Apr 24 18:33 /opt/bitnami/phabricator/data -> /bitnami/phabricator/data
root@4c6d86bfe91b:/# ls -lad /opt/bitnami/phabricator/data/* | head -n 5
drwxr-xr-x 61 daemon daemon 4096 Apr 12 12:43 /opt/bitnami/phabricator/data/00
drwxr-xr-x 56 daemon daemon 4096 Apr 12 12:43 /opt/bitnami/phabricator/data/01
drwxr-xr-x 63 daemon daemon 4096 Apr 12 12:19 /opt/bitnami/phabricator/data/02
drwxr-xr-x 69 daemon daemon 4096 Apr 16 21:52 /opt/bitnami/phabricator/data/03
drwxr-xr-x 68 daemon daemon 4096 Apr 12 12:34 /opt/bitnami/phabricator/data/04

diffs stuck at importing
```
root@4c6d86bfe91b:/# repository importing R11
R11:a581a3f39a85 Message, Change, Owners, Herald
R11:bec5c317eb9b Message, Change, Owners, Herald
```
and the error is the same
```
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000] [2019-04-24 19:20:09] EXCEPTION: (PhutilProxyException) Error while executing Task ID 420351. {>} (PhutilAggregateException) All storage engines failed to write file:
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]     - PhabricatorLocalDiskFileStorageEngine: CommandException: Command failed with error #1!
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       COMMAND
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       mkdir -p '/opt/bitnami/phabricator/data/1b/df'
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       STDOUT
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       (empty)
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       STDERR
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]       mkdir: cannot create directory '/opt/bitnami/phabricator/data/1b/df': Permission denied
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]        at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:403]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000] arcanist(head=stable, ref.stable=4d22e0f89f10), phabricator(head=stable, ref.stable=51d9453e5341), phutil(head=stable, ref.stable=e9bbfcb14353)
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #0 <#3> ExecFuture::resolvex() called at [<phutil>/src/future/exec/execx.php:17]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #1 <#3> execx(string, string) called at [<phabricator>/src/applications/files/engine/PhabricatorLocalDiskFileStorageEngine.php:58]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #2 <#3> PhabricatorLocalDiskFileStorageEngine::writeFile(string, array) called at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:552]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #3 <#3> PhabricatorFile::writeToEngine(PhabricatorLocalDiskFileStorageEngine, string, array) called at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:382]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #4 <#2> PhabricatorFile::buildFromFileData(string, array) called at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:448]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #5 <#2> PhabricatorFile::newFromFileData(string, array) called at [<phabricator>/src/applications/files/uploadsource/PhabricatorFileUploadSource.php:170]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #6 <#2> PhabricatorFileUploadSource::writeSingleFile() called at [<phabricator>/src/applications/files/uploadsource/PhabricatorFileUploadSource.php:76]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #7 <#2> PhabricatorFileUploadSource::uploadFile() called at [<phabricator>/src/applications/diffusion/query/DiffusionFileFutureQuery.php:114]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #8 <#2> DiffusionFileFutureQuery::executeQuery() called at [<phabricator>/src/applications/diffusion/query/DiffusionQuery.php:96]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #9 <#2> DiffusionQuery::execute() called at [<phabricator>/src/applications/diffusion/query/DiffusionFileFutureQuery.php:60]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #10 <#2> DiffusionFileFutureQuery::respondToConduitRequest(ConduitAPIRequest) called at [<phabricator>/src/applications/diffusion/conduit/DiffusionRawDiffQueryConduitAPIMethod.php:44]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #11 <#2> DiffusionRawDiffQueryConduitAPIMethod::getResult(ConduitAPIRequest) called at [<phabricator>/src/applications/diffusion/conduit/DiffusionQueryConduitAPIMethod.php:158]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #12 <#2> DiffusionQueryConduitAPIMethod::execute(ConduitAPIRequest) called at [<phabricator>/src/applications/conduit/method/ConduitAPIMethod.php:123]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #13 <#2> ConduitAPIMethod::executeMethod(ConduitAPIRequest) called at [<phabricator>/src/applications/conduit/call/ConduitCall.php:131]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #14 <#2> ConduitCall::executeMethod() called at [<phabricator>/src/applications/conduit/call/ConduitCall.php:81]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #15 <#2> ConduitCall::execute() called at [<phabricator>/src/applications/diffusion/query/DiffusionQuery.php:82]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #16 <#2> DiffusionQuery::callConduitWithDiffusionRequest(PhabricatorUser, DiffusionGitRequest, string, array) called at [<phabricator>/src/applications/differential/engine/DifferentialDiffExtractionEngine.php:57]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #17 <#2> DifferentialDiffExtractionEngine::newDiffFromCommit(PhabricatorRepositoryCommit) called at [<phabricator>/src/applications/differential/engine/DifferentialDiffExtractionEngine.php:248]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #18 <#2> DifferentialDiffExtractionEngine::updateRevisionWithCommit(DifferentialRevision, PhabricatorRepositoryCommit, array, PhabricatorDaemonContentSource) called at [<phabricator>/src/applications/repository/worker/commitmessageparser/PhabricatorRepositoryCommitMessageParserWorker.php:287]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #19 <#2> PhabricatorRepositoryCommitMessageParserWorker::updateCommitData(DiffusionCommitRef) called at [<phabricator>/src/applications/repository/worker/commitmessageparser/PhabricatorRepositoryCommitMessageParserWorker.php:42]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #20 <#2> PhabricatorRepositoryCommitMessageParserWorker::parseCommit(PhabricatorRepository, PhabricatorRepositoryCommit) called at [<phabricator>/src/applications/repository/worker/PhabricatorRepositoryCommitParserWorker.php:51]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #21 <#2> PhabricatorRepositoryCommitParserWorker::doWork() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:124]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #22 <#2> PhabricatorWorker::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/storage/PhabricatorWorkerActiveTask.php:158]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #23 <#2> PhabricatorWorkerActiveTask::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorTaskmasterDaemon.php:22]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #24 PhabricatorTaskmasterDaemon::run() called at [<phutil>/src/daemon/PhutilDaemon.php:219]
Daemon 165843 STDE [Wed, 24 Apr 2019 19:20:09 +0000]   #25 PhutilDaemon::execute() called at [<phutil>/scripts/daemon/exec/exec_daemon.php:131]
Daemon 165843 FAIL [Wed, 24 Apr 2019 19:20:09 +0000] Process exited with error 255.
```

Could this be related somehow to the volume itself? I haven't tried with a fully fresh installation and clearly re-using the same volume for data persistence, maybe something weird going on there?

**Comment by andresbono** [comment]
It may be related to that @arjunadeltoso. If you have the option, try a fresh install without volumes, just for testing.

Also, what are the permissions and ownership of `/bitnami/phabricator/data`? You can check it with:

```
ls -la /bitnami/phabricator
```

Which user is executing the phabricator process? You can execute:

```
ps aux
```
Can you create a folder with that user?

```
sudo -u <user> mkdir -p /opt/bitnami/phabricator/data/dir1/dir2
ls /opt/bitnami/phabricator/data/dir1
```
